title: My NLP Course
description: This is an NLP course webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # the base hostname & protocol for your site
theme: minima
